### ISSUE TITLE
The download link of the formatted CUB data is not available anymore 

### ISSUE THREAD

**Issue by zengguangjie** [Ruiding1/ComGAN#1]
I'm interested in your ComGAN model and willing to train your model.
The download link of the formatted CUB data is not available anymore, could you please share it again?
Thanks a lot!

**Comment by Ruiding1** [comment]
Of course, this is the new link [link](https://pan.baidu.com/s/14ItheH-YICns0ntbAQGS8w )[BaiDuYunDisk] and its extracted code: `2dc3`. Good luck with your experiment!
